_target_: src.losses.focal.FocalLoss
alpha: 1.0
gamma: 2.0
# 낮은 F1 점수를 가진 클래스들(3, 4, 7, 14)에 더 높은 가중치 적용
class_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 