# Main Hydra configuration file
# Replaces your existing configs/config.yaml

defaults:
  - _self_
  - experiment: default
  - model: resnet50
  - optimizer: adamw
  - scheduler: cosine_warm_restart
  - data: document
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Global settings
seed: 42
device: 'cuda'

# WandB Configuration (keeping your existing structure)
wandb:
  enabled: false
  project: "document-classifier"
  entity: null
  username: wchoi189
  tags: ["resnet50", "document-classification", "optimized", "high-perf-gpu"]
  notes: "ResNet-50 for 17-class document classification with 2.2:1 imbalance"
  
  # Logging settings
  log_frequency: 10
  log_images: true
  log_model: false
  log_gradients: false
  log_confusion_matrix: true
  
  # Advanced features
  watch_model: true
  log_code: true

# Paths configuration (keeping your existing structure)
paths:
  output_dir: "outputs"
  prediction_dir: "predictions"
  model_dir: "models"
  batch_dir: "batch"
  batch_summary_filename: "batch_summary.csv"

# Training configuration
train:
  epochs: 30
  batch_size: 32
  mixed_precision: true
  
  # Early stopping
  early_stopping:
    patience: 8
    metric: 'val_f1'
    mode: 'max'

# Data configuration
data:
  root_dir: "data/raw"
  csv_file: "data/raw/metadata/train.csv"
  meta_file: "data/raw/metadata/meta.csv"
  image_size: 224
  val_size: 0.2
  num_workers: 0
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  use_document_augmentation: false

# Logging and validation
logging:
  log_interval: 10
  memory_logging: true
  save_freq: 10
  save_best_only: false

validation:
  compute_class_metrics: true
  save_predictions: true
  plot_curves: true