# Hydra 기본 설정
defaults:
  - _self_
  - experiment: default
  - scheduler: cosine
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# 기본 설정
seed: 42
num_classes: 17

# 저장 설정
save:
  model_dir: "experiments"
  checkpoint_dir: "checkpoints"

# 학습 설정
training:
  batch_size: 16
  max_epochs: 100
  num_workers: 4
  patience: 30

# 모델 설정
model:
  name: "convnext"
  model_name: "convnext_large"
  pretrained: true
  dropout_rate: 0.5
  num_classes: 17

# 데이터셋 설정
dataset:
  name: "augmented_v2"
  train_csv: "data/train_fixed.csv"
  train_img_dir: "data/train"
  val_csv: "data/train_fixed.csv"
  val_img_dir: "data/train"
  # train_csv: "data/train_augmented2.csv"
  # train_img_dir: "data/train_augmented2"
  # val_csv: "data/val_augmented2.csv"
  # val_img_dir: "data/val_augmented2"
  # train_csv: "data/train_augmented(base+1+2).csv"
  # train_img_dir: "data/train_augmented(base+1+2)"
  # val_csv: "data/val_augmented(base+1+2).csv"
  # val_img_dir: "data/val_augmented(base+1+2)"
  # train_csv: "data/train_augmented_v2/train_augmented_v2.csv"
  # train_img_dir: "data/train_augmented_v2/images/"
  # val_csv: "data/val_augmented_v2/val_augmented_v2.csv"
  # val_img_dir: "data/val_augmented_v2/images/"

# 변환 설정
transform:
  name: "augmented_v2"
  image_size: 384

# 옵티마이저 설정
optimizer:
  name: "adamw"
  lr: 0.001
  weight_decay: 0.0001

# 스캐줄러 설정
scheduler:
  name: "cosine"
  # 스캐줄러별 설정은 각 스캐줄러 yaml 파일에서 관리
  # 또는 여기서 직접 파라미터 설정 가능
  params:
    T_max: 100
    # T_0: 10
    # T_mult: 2
    # eta_min: 0.0000001

# 손실 함수 설정
loss:
  # name: "cross_entropy"
  # label_smoothing: 0.0
  name : "focal"
  alpha: 1.0
  gamma: 2.0


  # 로깅 설정
logging:
  project_name: "document-classification"
  log_every_n_steps: 50
  save_top_k: 3

# S3 설정 (선택사항)
s3:
  enabled: false
  bucket_name: ""
  region_name: "us-east-1"