# Hydra 기본 설정
defaults:
  - _self_
  - experiment: default
  - scheduler: cosine
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# 기본 설정
seed: 42
num_classes: 17

# 새로운 parameters 섹션 추가
parameters:
  # 모델 관련 parameters
  model_parameters:
    embedding_dim: 512
    hidden_dim: 256
    num_layers: 4
    attention_heads: 8
    
  # 학습 관련 parameters
  training_parameters:
    gradient_accumulation_steps: 1
    warmup_ratio: 0.1
    max_grad_norm: 1.0
    scheduler_type: "cosine"
    
  # 데이터 관련 parameters
  data_parameters:
    max_length: 512
    truncation: true
    padding: "max_length"
    
  # 평가 관련 parameters
  evaluation_parameters:
    eval_steps: 500
    save_steps: 1000
    logging_steps: 100

# 저장 설정
save:
  model_dir: "experiments"
  checkpoint_dir: "checkpoints"

# 학습 설정
training:
  batch_size: 16
  max_epochs: 50
  num_workers: 4
  patience: 10

# 모델 설정
model:
  name: "resnet50"
  # model_name: "efficientnet-b3"
  pretrained: true
  dropout_rate: 0.5
  num_classes: 17

# 데이터셋 설정
dataset:
  name: "augmented"
  # train_csv: "data/train.csv"
  # train_img_dir: "data/train"
  # val_csv: "data/train.csv"
  # val_img_dir: "data/train"
  train_csv: "data/train_augmented.csv"
  train_img_dir: "data/train_augmented"
  val_csv: "data/val_augmented.csv"
  val_img_dir: "data/val_augmented"

# 변환 설정
transform:
  name: "augmented"
  image_size: 256

# 옵티마이저 설정
optimizer:
  name: "adamw"
  lr: 0.001
  weight_decay: 0.0001

# 스캐줄러 설정
scheduler:
  name: "cosine_warm_restart"
  # 스캐줄러별 설정은 각 스캐줄러 yaml 파일에서 관리
  # 또는 여기서 직접 파라미터 설정 가능
  params:
    T_0: 10
    T_mult: 2
    eta_min: 0.000001

# 손실 함수 설정
loss:
  name: "cross_entropy"
  label_smoothing: 0.0

# 로깅 설정
logging:
  project_name: "document-classification"
  log_every_n_steps: 50
  save_top_k: 3

# S3 설정 (선택사항)
s3:
  enabled: false
  bucket_name: ""
  region_name: "us-east-1"