# 하이드라 스윕 설정
defaults:
  - _self_
  - experiment: default
  - scheduler: cosine
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# 스윕 설정
hydra:
  sweeper:
    params:
      # 실험별 실행
      experiment: default,team1,team2,team3,team4,team5
      
      # 하이퍼파라미터 스윕
      optimizer.lr: 0.001,0.0001,0.00001
      training.batch_size: 16,32,64
      model.dropout_rate: 0.3,0.5,0.7
      
      # 모델 스윕
      model.model_name: efficientnet-b0,efficientnet-b4,efficientnet-b7

# 기본 설정
seed: 42
num_classes: 17

# 저장 설정
save:
  model_dir: "experiments"
  checkpoint_dir: "checkpoints"

# 학습 설정
training:
  batch_size: 32
  max_epochs: 100
  num_workers: 4
  patience: 30

# 모델 설정
model:
  name: "efficientnet"
  model_name: "efficientnet-b4"
  pretrained: true
  dropout_rate: 0.5
  num_classes: 17

# 데이터셋 설정
dataset:
  name: "augmented"
  train_csv: "data/train_augmented(base+1+2).csv"
  train_img_dir: "data/train_augmented(base+1+2)"
  val_csv: "data/val_augmented(base+1+2).csv"
  val_img_dir: "data/val_augmented(base+1+2)"

# 변환 설정
transform:
  name: "augmented"
  image_size: 224

# 옵티마이저 설정
optimizer:
  name: "adamw"
  lr: 0.001
  weight_decay: 0.0001

# 스캐줄러 설정
scheduler:
  name: "cosine"
  params:
    T_max: 100

# 손실 함수 설정
loss:
  name: "cross_entropy"
  label_smoothing: 0.0

# 로깅 설정
logging:
  project_name: "document-classification"
  log_every_n_steps: 50
  save_top_k: 3

# S3 설정
s3:
  enabled: false
  bucket_name: ""
  region_name: "us-east-1" 